from .funcs.sin import dsin
from .funcs.cos import dcos
from .funcs.e import de
from .funcs.log import dlog
from .funcs.relu import drelu
from .funcs.sigmoid import dsigmoid
from .funcs.tan import dtan
from .funcs.tanh import dtanh
from .funcs.softmax import dsoftmax
